xsltproc  --output bog.html /usr/share/sgml/docbook/xsl-stylesheets-1.53.0/html/docbook.xslbog.xml
#/usr/java/j2re1.4.1/bin/java org.apache.xalan.xslt.Process  -out bog.html  -in bog.xml  -xsl   /usr/share/sgml/docbook/xsl-stylesheets-1.53.0/html/docbook.xsl
