#! /bin/sh

FILES="
admin/bog/stikord.html.php
applikationer/bog/stikord.html.php
c/bog/stikord.html.php
dokumentation/bog/stikord.html.php
friheden/bog/stikord.html.php
kontorbruger/bog/stikord.html.php
program/bog/stikord.html.php
sikkerhed/bog/stikord.html.php
unix/bog/stikord.html.php
web/bog/stikord.html.php
wm/bog/stikord.html.php
"

./splitstikord.pl $FILES

for F in idx-*.html; do
	tidy -mq $F 
done

if [ -e idx-.symboler.html ]; then
	mv -f idx-.symboler.html idx-symboler.html
fi
