# $Id$

# Lokal makefile for dokumentationsbogen

# Definer lokale SGML filer, samt hvordan de kan laves
auto_sgml_filer:=$(auto_sgml_filer) usedtags_now.sgml

# Regel for at lave sgml filer
# TODO: Ikke medtage usedtags_now.sgml, hvis den findes! :-)
usedtags_now.sgml:	*.sgml
	cat *.sgml | ./usedtags.pl | sort -nr > usedtags_now.sgml
