<?php

/* HTML reference til selve bogen */
$boghref = "/linuxbog/program/";

/* Her er alle programmeringssprogene */
$proglang = array(
  "a60" => array(
    navn => "Algol60",
    link => "algol.html"
  ),
  "adb" => array(
    navn => "Ada",
    link => "ada.html"
  ),
  "awk-one" => array(
    navn => "AWK oneliner",
    link => "awk-one.html"
  ),
  "bas" => array(
    navn => "BASIC",
    link => "basic.html"
  ),
  "bet" => array(
    navn => "Beta?",
    link => "beta.html"
  ),
  "c" => array(
    navn => "C",
    link => "c.html"
  ),
  "qt" => array(
    navn => "C Qt",
    link => "qt.html"
  ),
  "gtk" => array(
    navn => "C GTK",
    link => "gtk.html"
  ),
  "kde" => array(
    navn => "C KDE",
    link => "kde.html"
  ),
  "cod" => array(
    navn => "Cobol",
    link => "cobol.html"
  ),
  "cc" => array(
    navn => "C++",
    link => "cc.html"
  ),
  "cml" => array(
    navn => "Comal?",
    link => "comal.html"
  ),
  "erl" => array(
    navn => "Erlang",
    link => "erlang.html"
  ),
  "exp" => array(
    navn => "Expect",
    link => "expect.html"
  ),
  "f" => array(
    navn => "Fortran",
    link => "fortran.html"
  ),
  "fs" => array(
    navn => "Forth",
    link => "forth.html"
  ),
  "scm" => array(
    navn => "Guile",
    link => "guile.html"
  ),
  "java" => array(
    navn => "Java",
    link => "java.html"
  ),
  "html" => array(
    navn => "JavaScript",
    link => "javascript.html"
  ),
  "occ" => array(
    navn => "KRoC",
    link => "kroc.html"
  ),
  "lisp" => array(
    navn => "Lisp",
    link => "lisp.html"
  ),
  "logo" => array(
    navn => "Logo",
    link => "logo.html"
  ),
  "mdl" => array(
    navn => "Modula",
    link => "modula.html"
  ),
  "obc" => array(
    navn => "Objective C",
    link => "objectivec.html"
  ),
  "oca" => array(
    navn => "Occam?",
    link => "occam.html"
  ),
  "pas" => array(
    navn => "Pascal",
    link => "pascal.html"
  ),
  "php" => array(
    navn => "PHP",
    link => "php.html"
  ),
  "pl" => array(
    navn => "Perl",
    link => "perl.html"
  ),
  "pl-one" => array(
    navn => "Perl-oneliner",
    link => "perl-one.html"
  ),
  "pl-cgi" => array(
    navn => "Perl-CGI",
    link => "perl-cgi.html"
  ),
  "prl" => array(
    navn => "Prolog",
    link => "prolog.html"
  ),
  "ps" => array(
    navn => "PostScript",
    link => "ps.html"
  ),
  "psql" => array(
    navn => "PostgreSQL",
    link => "postgresql.html"
  ),
  "py" => array(
    navn => "Python",
    link => "python.html"
  ),
  "rexx" => array(
    navn => "REXX",
    link => "rexx.html"
  ),
  "p" => array(
    navn => "RPilot",
    link => "rpilot.html"
  ),
  "she" => array(
    navn => "Scheme?",
    link => "scheme.html"
  ),
  "sh" => array(
    navn => "Shell/bash",
    link => "sh.html"
  ),
  "sh-cgi" => array(
    navn => "Shell CGI",
    link => "sh-cgi.html"
  ),
  "sml" => array(
    navn => "SML",
    link => "sml.html"
  ),
  "sm" => array(
    navn => "Sendmail",
    link => "sendmail.html"
  ),
  "st" => array(
    navn => "Smalltalk",
    link => "smalltalk.html"
  ),
  "tcl" => array(
    navn => "TCL",
    link => "tcl.html"
  ),
  "tk" => array(
    navn => "TK",
    link => "tk.html"
  ),
  "trn" => array(
    navn => "Trine",
    link => "trine.html"
  ),
  "tur" => array(
    navn => "Turing-maskine",
    link => "turing.html"
  )
);

$examp = array(
  "hello" => "Det klassiske \"Hello, world!\" program. Programmet udskriver \"Hello, world!\", efterfulgt af linie-skift hvis programmeringssproget kan. Dette er et minimalt program der viser start og slut, samt en kommentar.",
  "udskriv" => "Et lille eksempel på åbning af fil. Filnavnet angives på kommando-linien. Der testes for om filen findes, hvis ikke, udskrives en fejl. Findes filen, udskrives den på stdout med linienumre. Tast Q ENTER for at afslutte.",
  "smart" => "Et smart eksempel som dette sprog er godt til"
);

?>
