#!/bin/sh

# Dette er bare det script jeg bruger til opdatering / chlor

export FIL=linuxbog-program-eksempler.tgz
rm -f program/eksempler/$FIL
tar czvf $FIL program/eksempler/[a-z]*
mv $FIL program/eksempler

