#! /bin/sh
# Filnavn: menu1
dialog --menu "Hvem var en berømt astronom?" 0 0 0 \
	a "Axel Brahe" \
	o "Otto Brahe" \
	t "Tyge Brahe" \
	2>/tmp/svar || exit
read SVAR </tmp/svar && rm -f /tmp/svar
echo "Svaret var: $SVAR"
