#! /bin/sh
# Filnavn: menu2
dialog --menu "Hvem var en berømt astronom?" 0 0 0 \
	a "Axel Brahe" \
	o "Otto Brahe" \
	t "Tyge Brahe" \
	2>/tmp/svar || exit
read SVAR </tmp/svar && rm -f /tmp/svar
case $SVAR in
	t)
		echo "Korrekt"
		;;
	*)
		echo "Forkert. Svaret er Tyge."
		;;
esac
