# $Id$

# Lokal makefile for signaturbogen

# Definer lokale SGML filer, samt hvordan de kan laves
auto_sgml_filer:=$(auto_sgml_filer) req-kmd-ca.sgml

# Regel for at lave sgml filer
req-kmd-ca.sgml:	eksempler/req-kmd-ca.pl
	eksempler/perl2sgml.pl < eksempler/req-kmd-ca.pl > req-kmd-ca.sgml
