#!/bin/sh

# Dette script bootstrapper toolchainen til at lave linux bøgerne med i underkatalogerne. 

#echo Installerer m4 makroer && \
# aclocal -I config && \
aclocal && \
#echo Creating headers && \
#autoheader && \
#echo Kører automake && \
automake --foreign --add-missing --copy && \
#echo Patching toplevel Makefile.in && \
#cat Makefile.in | sed 's/cp -pr \$\$\/\$/cp -pr \$\$d\/\$/' > Makefile.in.patch && \
#mv -f Makefile.in.patch Makefile.in && \
#echo Laver configure script && \
autoconf && true || false
