db2html  -V use-id-as-filename=t -V html-index=t bog.sgml
collateindex.pl -s Symboler -t Stikordsregister  -g -i stikord  -o stikord.sgml bog/HTML.index
db2html  -V use-id-as-filename=t bog.sgml


xsltproc  --output bog.html /usr/share/sgml/docbook/xsl-stylesheets-1.53.0/html/docbook.xsl
bog.xml


/usr/java/j2re1.4.1/bin/java org.apache.xalan.xslt.Process  -out bog.html  -in bog.xml  -xsl   /usr/share/sgml/docbook/xsl-stylesheets-1.53.0/html/docbook.xsl
