#!/bin/sh
export PATH=/sbin:/usr/bin:/bin
clear
# Ens eksterne netkort ud mod Internettet.
# Eksempel EXTIF="ppp0", ippp0 eller "eth0"
EXTIF="ppp0"

# Det interne netkort.
# Eksempel INTIF="eth0"
INTIF="eth0"

# Hvis man via sit netkort eller ppp adapter får en dynamisk IP addresse fra
# sin Internet udbyder skal DHCP stå til yes.
DHCP="yes"

# Hvis denne sættes til yes vil ALT udp trafik ind til portene 55000 til 65535
# blive tilladt ind til EXTIF på firewallen.
UDPINOK=""

# Ens IP adresse på ens eksterne netkort eller ppp adapter.
EXTIP=`ifconfig | grep -A 4 $EXTIF | awk '/inet/ { print $2 } ' | sed -e s/addr://`

if [ "$EXTIP" = '' ]; then
   echo "Kan ikke finde IP adressen på $EXTIF "
   exit 1
fi

# Alle IP adresser.
ANYIP="0.0.0.0/0.0.0.0"

# IP adresse på det interne netværk.
INTLAN=`ifconfig | grep -A 4 $INTIF | awk '/inet/ { print $2 } ' | sed -e s/addr://`"/"`ifconfig | grep -A 4 $INTIF | awk '/Mask/ { print $4 } ' | sed -e s/Mask://`

if [ "$INTLAN" = '' ]; then
   echo "Kan ikke finde IP adressen på $INTLAN ..."
   echo
   exit 1
fi

DNS1=`awk -vnum=1 'BEGIN{i=1}/nameserver/{ns[i]=$2;i++}END{print ns[num]}' /etc/resolv.conf`
DNS2=`awk -vnum=2 'BEGIN{i=1}/nameserver/{ns[i]=$2;i++}END{print ns[num]}' /etc/resolv.conf`
DNS3=`awk -vnum=3 'BEGIN{i=1}/nameserver/{ns[i]=$2;i++}END{print ns[num]}' /etc/resolv.conf`

if [ "$DNS1" = '' ]; then
   echo "Kan ikke finde nogen DNS server i resolv.conf."
   exit 1
fi

# Slår IP forwarding til
echo "1" > /proc/sys/net/ipv4/ip_forward

# Slår IP Spoofing attacks fra.
for file in /proc/sys/net/ipv4/conf/*/rp_filter
do
  echo "2" > $file
done

# Slår syn-cookies til (syn-flooding attacks) hvis support er kompileret i kernen.
if [ -f /proc/sys/net/ipv4/tcp_syncookies ]; then
  echo "1" >/proc/sys/net/ipv4/tcp_syncookies
fi

# Sætter ip_dynaddr til 1 hvis DHCP = yes.
if [ "`echo $DHCP | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
  echo "1" > /proc/sys/net/ipv4/ip_dynaddr
 else
  echo "0" > /proc/sys/net/ipv4/ip_dynaddr
fi

# Slår source routing fra
for file in /proc/sys/net/ipv4/conf/*/accept_source_route
do
 echo "0" > $file
done

# Slår ICMP redirect fra
for file in /proc/sys/net/ipv4/conf/*/accept_redirects
do
 echo "0" > $file
done

# Slår IP Always Defrag til.
echo "1" > /proc/sys/net/ipv4/ip_always_defrag

# Liste over porte der åbnes lokalt på firewallen, når der laves en forbindelse ud.
echo "55000 60999" >/proc/sys/net/ipv4/ip_local_port_range

# Slet alle regler i kæderne
ipchains -F
ipchains -X

# Ændre INPUT til DENY og OUTPUT og FORWARD kæden til REJECT
ipchains -P input DENY
ipchains -P forward REJECT
ipchains -P output REJECT

# Ændre IP masquerading timeouts.
ipchains -M -S 7200 10 160

# Load disse moduler til IP MASQ

# Bruges til noget video konference.
#if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_cuseeme.o ]; then
#   CUSEEME="yes"
#  if ! [ "`cat /proc/modules | awk '/ip_masq_cuseeme/ { print $1 }'`" = ip_masq_cuseeme ]; then 
#   insmod /lib/modules/`uname -r`/ipv4/ip_masq_cuseeme.o
#  fi
#fi

# Bruges så aktiv FTP virker.
if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_ftp.o ]; then
   FTP="yes"
  if ! [ "`cat /proc/modules | awk '/ip_masq_ftp/ { print $1 }'`" = ip_masq_ftp ]; then 
   insmod /lib/modules/`uname -r`/ipv4/ip_masq_ftp.o
  fi
fi

# Bruges til IRC så fil overførelse virker.
if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_irc.o ]; then
   IRC="yes"
  if ! [ "`cat /proc/modules | awk '/ip_masq_irc/ { print $1 }'`" = ip_masq_irc ]; then 
   insmod /lib/modules/`uname -r`/ipv4/ip_masq_irc.o
  fi
fi

# Bruges til Quake over Internettet
if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_quake.o ]; then
   QUAKE="yes"
  if ! [ "`cat /proc/modules | awk '/ip_masq_quake/ { print $1 }'`" = ip_masq_quake ]; then 
   insmod /lib/modules/`uname -r`/ipv4/ip_masq_quake.o
  fi
fi

# Bruges så UDP virker med Real Audio
if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_raudio.o ]; then
   RAUDIO="yes"
  if ! [ "`cat /proc/modules | awk '/ip_masq_raudio/ { print $1 }'`" = ip_masq_raudio ]; then 
   insmod /lib/modules/`uname -r`/ipv4/ip_masq_raudio.o
  fi
fi

# Bruges til live video over Internettet
#if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_vdolive.o ]; then
#   VDOLIVE="yes"
#  if ! [ "`cat /proc/modules | awk '/ip_masq_vdolive/ { print $1 }'`" = ip_masq_vdolive ]; then 
#   insmod /lib/modules/`uname -r`/ipv4/ip_masq_vdolive.o
#  fi
#fi

# Bruges til ICQ
if [ -f /lib/modules/`uname -r`/ipv4/ip_masq_icq.o ]; then
   ICQ="yes"
  if ! [ "`cat /proc/modules | awk '/ip_masq_icq/ { print $1 }'`" = ip_masq_icq ]; then 
   insmod /lib/modules/`uname -r`/ipv4/ip_masq_icq.o
  fi
fi

# IP adresse som siger den har local loopback's IP adresse skal nægtes og logges
ipchains -A input -s 127.0.0.1/32 -i $EXTIF -l -j DENY

# IP adresse som siger den har EXTIP IP adresse skal nægtes og logges
ipchains -A input -s $EXTIP -i $EXTIF -l -j DENY

# IP adresse som siger den har en IP adresse i det "private" og multicast områdeskal nægtes og logges.
ipchains -A input -s 10.0.0.0/8 -i $EXTIF -l -j DENY
ipchains -A input -s 172.16.0.0/12 -i $EXTIF -l -j DENY
ipchains -A input -s 192.168.0.0/16 -i $EXTIF -l -j DENY
ipchains -A input -s 224.0.0.0/4 -i $EXTIF -l -j DENY
ipchains -A input -s 240.0.0.0/5 -i $EXTIF -l -j DENY

# Acceptere DHCP retur trafik ind hvis man ikke har fast IP adresse
if [ "`echo $DHCP | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
  ipchains -A input -i $EXTIF -p udp -s $ANYIP 67 -d 255.255.255.255/0 68 -j ACCEPT
fi 

# Acceptere DHCP retur trafik ud hvis man ikke har fast IP adresse
if [ "`echo $DHCP | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
  ipchains -A output -i $EXTIF -p udp -s 255.255.255.255/0 68 -d $ANYIP 67 -j ACCEPT
fi 

# Acceptere DHCP trafik ind og ud af $INTIF hvis man kører en DHCP server
# på firewall maskinen.
if [ "`ps -C dhcpd | grep dhcpd | awk ' { print $4 }'`" = dhcpd ]; then
  ipchains -A input -i $INTIF -p udp -s 255.255.255.255/0 68 -d $ANYIP 67 -j ACCEPT
  ipchains -A output -i $INTIF -p udp -s $ANYIP 67 -d 255.255.255.255/0 68 -j ACCEPT
fi

# Internt LAN ind til firewall er tilladt
ipchains -A input -s $INTLAN -i $INTIF -j ACCEPT

# Alt retur trafik ud af firewallen til internt LAN er tilladt 
ipchains -A output -d $INTLAN -i $INTIF -j ACCEPT

# Alt trafik som bliver forwarded videre til det eksterne netkort skal MASQ
ipchains -A forward -s $INTLAN -i $EXTIF -j MASQ

# Tillad kun TCP retur trafik.
ipchains -A input -i $EXTIF ! -y -p tcp -s $ANYIP -d $EXTIP 55000:65535 -j ACCEPT

# Tillad ALT UDP trafik til portene 55000 til 65535, der er INGEN garanti for
# at dette er retur trafik til ens firewall eller en forbindelse til et service
if [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
   ipchains -A input -i $EXTIF -s $ANYIP -d $EXTIP 55000:65535 -p udp -j ACCEPT
fi

# Tillad kun trafik ud fra EXTIF fra EXTIP IP adresse.
ipchains -A output -i $EXTIF -p tcp -s $EXTIP 55000:65535 -d 0/0 -j ACCEPT
ipchains -A output -i $EXTIF -p udp -s $EXTIP 55000:65535 -d 0/0 -j ACCEPT

# Afvis Auth trafik ind.
ipchains -A input -i $EXTIF -p tcp -s $ANYIP 1024:65535 -d $EXTIP 113 -j REJECT

# Tillad kun DNS retur trafik fra DNS servere der står i /etc/resolv.conf
if ! [ "$DNS1" = "" ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $DNS1 53 -d $EXTIP 55000:65535 -j ACCEPT
   fi
fi    

if ! [ "$DNS2" = "" ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $DNS3 53 -d $EXTIP 55000:65535 -j ACCEPT
   fi
fi    

if ! [ "$DNS3" = "" ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $DNS3 53 -d $EXTIP 55000:65535 -j ACCEPT
   fi
fi    

# Acceptere aktivt FTP-data fra Internet til firewall hvis FTP modul er loadet
if [ "`cat /proc/modules | awk '/ip_masq_ftp/ { print $1 }'`" = ip_masq_ftp ]; then
    ipchains -A input -i $EXTIF -p tcp -s $ANYIP 20 -d $EXTIP 55000:65535 -y -j ACCEPT
fi

# Acceptere ICQ trafik fra Internet til firewall hvis ICQ modul er loadet
if [ "`cat /proc/modules | awk '/ip_masq_icq/ { print $1 }'`" = ip_masq_icq ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $ANYIP 4000 -d $EXTIP 55000:65535 -j ACCEPT
   fi
fi

# Acceptere Real Audio trafik fra Internet til firewall hvis RAUDIO modul er loadet
if [ "`cat /proc/modules | awk '/ip_masq_raudio/ { print $1 }'`" = ip_masq_raudio ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $ANYIP 6970:7170 -d $EXTIP 55000:65535 -j ACCEPT
   fi
fi

# Acceptere CUSEEME trafik fra Internet til firewall hvis CUSEEME modul er loadet
if [ "`cat /proc/modules | awk '/ip_masq_cuseeme/ { print $1 }'`" = ip_masq_cuseeme ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $ANYIP 7648:7649 -d $EXTIP 55000:65535 -j ACCEPT
    ipchains -A input -i $EXTIF -p udp -s $ANYIP 24032 -d $EXTIP 55000:65535 -j ACCEPT    
   fi
fi

# Acceptere QUAKE trafik fra Internet til firewall hvis QUAKE modul er loadet
if [ "`cat /proc/modules | awk '/ip_masq_quake/ { print $1 }'`" = ip_masq_quake ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    ipchains -A input -i $EXTIF -p udp -s $ANYIP 26000 -d $EXTIP 55000:65535 -j ACCEPT
    ipchains -A input -i $EXTIF -p udp -s $ANYIP 1025:1200 -d $EXTIP 55000:65535 -j ACCEPT    
   fi
fi

# Tillad source-quench, echo-request, fragmentation-neeeded, parameter-problem 
# port-unreachable og time-exceeded ICMP trafik ud.
ipchains -A output -i $EXTIF -s $EXTIP echo-request -p icmp -j ACCEPT
ipchains -A output -i $EXTIF -s $EXTIP source-quench -p icmp -j ACCEPT
ipchains -A output -i $EXTIF -s $EXTIP time-exceeded -p icmp -j ACCEPT
ipchains -A output -i $EXTIF -s $EXTIP parameter-problem -p icmp -j ACCEPT
ipchains -A output -i $EXTIF -s $EXTIP fragmentation-needed -p icmp -j ACCEPT
ipchains -A output -i $EXTIF -s $EXTIP port-unreachable -p icmp -j ACCEPT

# Tillad source-quench, echo-reply, destination-unreachable, parameter-problem 
# og time-exceeded ICMP trafik ind.
ipchains -A input -i $EXTIF -s $ANYIP echo-reply -p icmp -j ACCEPT
ipchains -A input -i $EXTIF -s $ANYIP source-quench -p icmp -j ACCEPT
ipchains -A input -i $EXTIF -s $ANYIP time-exceeded -p icmp -j ACCEPT
ipchains -A input -i $EXTIF -s $ANYIP parameter-problem -p icmp -j ACCEPT
ipchains -A input -i $EXTIF -s $ANYIP destination-unreachable -p icmp -j ACCEPT


# Tillad ALT UDP trafik til portene 55000 til 65535, der er INGEN garanti for
# at dette er retur trafik til ens firewall eller en forbindelse til en service
ipchains -A input -i $EXTIF -s $ANYIP -d $EXTIP 55000:65535 -p udp -j ACCEPT


# Hvis /etc/firewall.debug findes, så logges alle INPUT og OUTPUT pakker som ikke
# accepteres, derved kan man via /var/log/messages se hvad der eventuelt skal
# åbnes for.
if [ -f /etc/firewall.debug ]; then
  ipchains -A input -l
  ipchains -A output -l
fi

# Hvis /etc/firewall.debug findes, så vises de variabler og de ting som script'et
# selv finder ud af.
if [ -f /etc/firewall.debug ]; then
 if [ "`echo $DHCP | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
  echo "Du får dynamisk IP tildelt fra din ISP til dit interface $EXTIF"
 fi
  echo "Dit interface ud mod Internet er: $EXTIF"
  echo "IP adressen på dit interface $EXTIF ud mod Internet er: $EXTIP"
  echo "Dit interface ud mod dit LAN er: $INTIF"
  echo "IP adressen og netmasken på dit LAN interface er: $INTLAN"
 if ! [ "$DNS1" = "" ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    echo "Din 1. DNS server i resolv.conf er: $DNS1"
   fi
 fi
 if ! [ "$DNS2" = "" ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    echo "Din 2. DNS server i resolv.conf er: $DNS2"
   fi
 fi
 if ! [ "$DNS3" = "" ]; then
   if ! [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
    echo "Din 3. DNS server i resolv.conf er: $DNS3"
   fi
 fi
 if [ "`echo $UDPINOK | tr '[A-Z]' '[a-z]'`" = "yes" ]; then
  echo "ALT UDP trafik til portene 55000:65535 er tilladt !!"
 fi
 if [ "`ps -C dhcpd | grep dhcpd | awk ' { print $4 }'`" = dhcpd ]; then
  echo "Du kører en DHCP server og der er lavet INPUT og OUTPUT regler for dette."
 fi
  echo "IP MASQ modulerne bliver loadet i kataloget:" /lib/modules/`uname -r`/ipv4/
 if [ "$FTP" = "yes" ]; then
  echo "IP MASQ: FTP modul er installeret."
 else
  echo "IP MASQ: FTP modul er ikke installeret."
 fi
 if [ "$CUSEEME" = "yes" ]; then
  echo "IP MASQ: CUSEEME modul er installeret."
 else
  echo "IP MASQ: CUSEEME modul er ikke installeret."
 fi
 if [ "$ICQ" = "yes" ]; then
  echo "IP MASQ: ICQ modul er installeret."
 else
  echo "IP MASQ: ICQ modul er ikke installeret."
 fi
 if [ "$IRC" = "yes" ]; then
  echo "IP MASQ: IRC modul er installeret."
 else
  echo "IP MASQ: IRC modul er ikke installeret."
 fi
 if [ "$QUAKE" = "yes" ]; then
  echo "IP MASQ: QUAKE modul er installeret."
 else
  echo "IP MASQ: QUAKE modul er ikke installeret."
 fi
 if [ "$RAUDIO" = "yes" ]; then
  echo "IP MASQ: RAUDIO modul er installeret."
 else
  echo "IP MASQ: RAUDIO modul er ikke installeret."
 fi
 if [ "$VDOLIVE" = "yes" ]; then
  echo "IP MASQ: VDOLIVE modul er installeret."
 else
  echo "IP MASQ: VDOLIVE modul er ikke installeret."
 fi
  echo "Hvis nogen af disse omlysninger er forkerte skal du rette dem i scriptet."
fi
